from pathlib import Path
from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *
from .resources_rc import *


class UiMainWindow(object):
    def __init__(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QSize(940, 560))
        self.mainWindowWidget = QWidget(MainWindow)
        self.mainWindowWidget.setObjectName(u"styleSheet")
        font = QFont()
        font.setFamily(u"Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.mainWindowWidget.setFont(font)
        self.mainWindowWidget.setStyleSheet((Path(__file__).parent.parent / "themes" / "py_dracula_dark.qss").read_text())
        self.windowMargins = QVBoxLayout(self.mainWindowWidget)
        self.windowMargins.setSpacing(0)
        self.windowMargins.setObjectName(u"appMargins")
        self.windowMargins.setContentsMargins(10, 10, 10, 10)
        self.bgApp = QFrame(self.mainWindowWidget)
        self.bgApp.setObjectName(u"bgApp")
        self.bgApp.setStyleSheet(u"")
        self.bgApp.setFrameShape(QFrame.NoFrame)
        self.bgApp.setFrameShadow(QFrame.Raised)
        self.appLayout = QHBoxLayout(self.bgApp)
        self.appLayout.setSpacing(0)
        self.appLayout.setObjectName(u"appLayout")
        self.appLayout.setContentsMargins(0, 0, 0, 0)
        self.leftMenuBg = QFrame(self.bgApp)
        self.leftMenuBg.setObjectName(u"leftMenuBg")
        self.leftMenuBg.setMinimumSize(QSize(60, 0))
        self.leftMenuBg.setMaximumSize(QSize(60, 16777215))
        self.leftMenuBg.setFrameShape(QFrame.NoFrame)
        self.leftMenuBg.setFrameShadow(QFrame.Raised)
        self.verticalLayout_3 = QVBoxLayout(self.leftMenuBg)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.topLogoInfo = QFrame(self.leftMenuBg)
        self.topLogoInfo.setObjectName(u"topLogoInfo")
        self.topLogoInfo.setMinimumSize(QSize(0, 50))
        self.topLogoInfo.setMaximumSize(QSize(16777215, 50))
        self.topLogoInfo.setFrameShape(QFrame.NoFrame)
        self.topLogoInfo.setFrameShadow(QFrame.Raised)
        self.topLogo = QFrame(self.topLogoInfo)
        self.topLogo.setObjectName(u"topLogo")
        self.topLogo.setGeometry(QRect(10, 5, 42, 42))
        self.topLogo.setMinimumSize(QSize(42, 42))
        self.topLogo.setMaximumSize(QSize(42, 42))
        self.topLogo.setFrameShape(QFrame.NoFrame)
        self.topLogo.setFrameShadow(QFrame.Raised)
        self.titleLeftApp = QLabel(self.topLogoInfo)
        self.titleLeftApp.setObjectName(u"titleLeftApp")
        self.titleLeftApp.setGeometry(QRect(70, 8, 160, 20))
        font1 = QFont()
        font1.setFamily(u"Segoe UI Semibold")
        font1.setPointSize(12)
        font1.setBold(False)
        font1.setItalic(False)
        self.titleLeftApp.setFont(font1)
        self.titleLeftApp.setAlignment(Qt.AlignLeading | Qt.AlignLeft | Qt.AlignTop)
        self.titleLeftDescription = QLabel(self.topLogoInfo)
        self.titleLeftDescription.setObjectName(u"titleLeftDescription")
        self.titleLeftDescription.setGeometry(QRect(70, 27, 160, 16))
        self.titleLeftDescription.setMaximumSize(QSize(16777215, 16))
        font2 = QFont()
        font2.setFamily(u"Segoe UI")
        font2.setPointSize(8)
        font2.setBold(False)
        font2.setItalic(False)
        self.titleLeftDescription.setFont(font2)
        self.titleLeftDescription.setAlignment(Qt.AlignLeading | Qt.AlignLeft | Qt.AlignTop)

        self.verticalLayout_3.addWidget(self.topLogoInfo)

        self.leftMenuFrame = QFrame(self.leftMenuBg)
        self.leftMenuFrame.setObjectName(u"leftMenuFrame")
        self.leftMenuFrame.setFrameShape(QFrame.NoFrame)
        self.leftMenuFrame.setFrameShadow(QFrame.Raised)
        self.verticalMenuLayout = QVBoxLayout(self.leftMenuFrame)
        self.verticalMenuLayout.setSpacing(0)
        self.verticalMenuLayout.setObjectName(u"verticalMenuLayout")
        self.verticalMenuLayout.setContentsMargins(0, 0, 0, 0)
        self.toggleBox = QFrame(self.leftMenuFrame)
        self.toggleBox.setObjectName(u"toggleBox")
        self.toggleBox.setMaximumSize(QSize(16777215, 45))
        self.toggleBox.setFrameShape(QFrame.NoFrame)
        self.toggleBox.setFrameShadow(QFrame.Raised)
        self.verticalLayout_4 = QVBoxLayout(self.toggleBox)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.toggleButton = QPushButton(self.toggleBox)
        self.toggleButton.setObjectName(u"toggleButton")
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toggleButton.sizePolicy().hasHeightForWidth())
        self.toggleButton.setSizePolicy(sizePolicy)
        self.toggleButton.setMinimumSize(QSize(0, 45))
        self.toggleButton.setFont(font)
        self.toggleButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.toggleButton.setLayoutDirection(Qt.LeftToRight)
        self.toggleButton.setStyleSheet(u"background-image: url(:/icons/images/icons/icon_menu.png);")

        self.verticalLayout_4.addWidget(self.toggleButton)

        self.verticalMenuLayout.addWidget(self.toggleBox)

        self.topMenu = QFrame(self.leftMenuFrame)
        self.topMenu.setObjectName(u"topMenu")
        self.topMenu.setFrameShape(QFrame.NoFrame)
        self.topMenu.setFrameShadow(QFrame.Raised)
        self.verticalLayout_8 = QVBoxLayout(self.topMenu)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)

        # Kafka Button
        self.btnKafka = QPushButton(self.topMenu)
        self.btnKafka.setObjectName(u"btnKafka")
        sizePolicy.setHeightForWidth(self.btnKafka.sizePolicy().hasHeightForWidth())
        self.btnKafka.setSizePolicy(sizePolicy)
        self.btnKafka.setMinimumSize(QSize(0, 45))
        self.btnKafka.setFont(font)
        self.btnKafka.setCursor(QCursor(Qt.PointingHandCursor))
        self.btnKafka.setLayoutDirection(Qt.LeftToRight)
        self.btnKafka.setStyleSheet(u"background-image: url(:/icons/images/icons/cil-cloudy.png);")
        self.verticalLayout_8.addWidget(self.btnKafka)
        # end kafka Button

        # Login Window Button
        self.btnLogin = QPushButton(self.topMenu)
        self.btnLogin.setObjectName(u"btnLogin")
        sizePolicy.setHeightForWidth(self.btnLogin.sizePolicy().hasHeightForWidth())
        self.btnLogin.setSizePolicy(sizePolicy)
        self.btnLogin.setMinimumSize(QSize(0, 45))
        self.btnLogin.setFont(font)
        self.btnLogin.setCursor(QCursor(Qt.PointingHandCursor))
        self.btnLogin.setLayoutDirection(Qt.LeftToRight)
        self.btnLogin.setStyleSheet(u"background-image: url(:/icons/images/icons/cil-user.png);")
        self.verticalLayout_8.addWidget(self.btnLogin)
        # End Login Window Button

        # Register Window Button
        self.btnRegister = QPushButton(self.topMenu)
        self.btnRegister.setObjectName(u"btnRegister")
        sizePolicy.setHeightForWidth(self.btnRegister.sizePolicy().hasHeightForWidth())
        self.btnRegister.setSizePolicy(sizePolicy)
        self.btnRegister.setMinimumSize(QSize(0, 45))
        self.btnRegister.setFont(font)
        self.btnRegister.setCursor(QCursor(Qt.PointingHandCursor))
        self.btnRegister.setLayoutDirection(Qt.LeftToRight)
        self.btnRegister.setStyleSheet(u"background-image: url(:/icons/images/icons/cil-user-follow.png);")
        self.verticalLayout_8.addWidget(self.btnRegister)
        # End register Window Button

        # Call Window Button
        self.btnCall = QPushButton(self.topMenu)
        self.btnCall.setObjectName(u"btnRegister")
        sizePolicy.setHeightForWidth(self.btnCall.sizePolicy().hasHeightForWidth())
        self.btnCall.setSizePolicy(sizePolicy)
        self.btnCall.setMinimumSize(QSize(0, 45))
        self.btnCall.setFont(font)
        self.btnCall.setCursor(QCursor(Qt.PointingHandCursor))
        self.btnCall.setLayoutDirection(Qt.LeftToRight)
        self.btnCall.setStyleSheet(u"background-image: url(:/icons/images/icons/cil-laptop.png);")
        self.verticalLayout_8.addWidget(self.btnCall)
        # End Call Window Button

        # change theme button
        self.btnChangeTheme = QPushButton(self.topMenu)
        self.btnChangeTheme.setObjectName(u"btnChangeTheme")
        sizePolicy.setHeightForWidth(self.btnChangeTheme.sizePolicy().hasHeightForWidth())
        self.btnChangeTheme.setSizePolicy(sizePolicy)
        self.btnChangeTheme.setMinimumSize(QSize(0, 45))
        self.btnChangeTheme.setFont(font)
        self.btnChangeTheme.setCursor(QCursor(Qt.PointingHandCursor))
        self.btnChangeTheme.setLayoutDirection(Qt.LeftToRight)
        self.btnChangeTheme.setStyleSheet(u"background-image: url(:/icons/images/icons/cil-star.png);")
        self.verticalLayout_8.addWidget(self.btnChangeTheme)
        # change theme button end

        self.verticalMenuLayout.addWidget(self.topMenu, 0, Qt.AlignTop)

        self.verticalLayout_3.addWidget(self.leftMenuFrame)

        self.appLayout.addWidget(self.leftMenuBg)

        self.contentBox = QFrame(self.bgApp)
        self.contentBox.setObjectName(u"contentBox")
        self.contentBox.setFrameShape(QFrame.NoFrame)
        self.contentBox.setFrameShadow(QFrame.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.contentBox)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.contentTopBg = QFrame(self.contentBox)
        self.contentTopBg.setObjectName(u"contentTopBg")
        self.contentTopBg.setMinimumSize(QSize(0, 50))
        self.contentTopBg.setMaximumSize(QSize(16777215, 50))
        self.contentTopBg.setFrameShape(QFrame.NoFrame)
        self.contentTopBg.setFrameShadow(QFrame.Raised)
        self.horizontalLayout = QHBoxLayout(self.contentTopBg)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 10, 0)
        self.leftBox = QFrame(self.contentTopBg)
        self.leftBox.setObjectName(u"leftBox")
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.leftBox.sizePolicy().hasHeightForWidth())
        self.leftBox.setSizePolicy(sizePolicy1)
        self.leftBox.setFrameShape(QFrame.NoFrame)
        self.leftBox.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_3 = QHBoxLayout(self.leftBox)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.titleRightInfo = QLabel(self.leftBox)
        self.titleRightInfo.setObjectName(u"titleRightInfo")
        sizePolicy2 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.titleRightInfo.sizePolicy().hasHeightForWidth())
        self.titleRightInfo.setSizePolicy(sizePolicy2)
        self.titleRightInfo.setMaximumSize(QSize(16777215, 45))
        self.titleRightInfo.setFont(font)
        self.titleRightInfo.setAlignment(Qt.AlignLeading | Qt.AlignLeft | Qt.AlignVCenter)

        self.horizontalLayout_3.addWidget(self.titleRightInfo)

        self.horizontalLayout.addWidget(self.leftBox)

        self.rightButtons = QFrame(self.contentTopBg)
        self.rightButtons.setObjectName(u"rightButtons")
        self.rightButtons.setMinimumSize(QSize(0, 28))
        self.rightButtons.setFrameShape(QFrame.NoFrame)
        self.rightButtons.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.rightButtons)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)

        self.minimizeAppBtn = QPushButton(self.rightButtons)
        self.minimizeAppBtn.setObjectName(u"minimizeAppBtn")
        self.minimizeAppBtn.setMinimumSize(QSize(28, 28))
        self.minimizeAppBtn.setMaximumSize(QSize(28, 28))
        self.minimizeAppBtn.setCursor(QCursor(Qt.PointingHandCursor))
        icon2 = QIcon()
        icon2.addFile(u":/icons/images/icons/icon_minimize.png", QSize(), QIcon.Normal, QIcon.Off)
        self.minimizeAppBtn.setIcon(icon2)
        self.minimizeAppBtn.setIconSize(QSize(20, 20))

        self.horizontalLayout_2.addWidget(self.minimizeAppBtn)

        self.maximizeRestoreAppBtn = QPushButton(self.rightButtons)
        self.maximizeRestoreAppBtn.setObjectName(u"maximizeRestoreAppBtn")
        self.maximizeRestoreAppBtn.setMinimumSize(QSize(28, 28))
        self.maximizeRestoreAppBtn.setMaximumSize(QSize(28, 28))
        font3 = QFont()
        font3.setFamily(u"Segoe UI")
        font3.setPointSize(10)
        font3.setBold(False)
        font3.setItalic(False)
        font3.setStyleStrategy(QFont.PreferDefault)
        self.maximizeRestoreAppBtn.setFont(font3)
        self.maximizeRestoreAppBtn.setCursor(QCursor(Qt.PointingHandCursor))
        icon3 = QIcon()
        icon3.addFile(u":/icons/images/icons/icon_maximize.png", QSize(), QIcon.Normal, QIcon.Off)
        self.maximizeRestoreAppBtn.setIcon(icon3)
        self.maximizeRestoreAppBtn.setIconSize(QSize(20, 20))

        self.horizontalLayout_2.addWidget(self.maximizeRestoreAppBtn)

        self.closeAppBtn = QPushButton(self.rightButtons)
        self.closeAppBtn.setObjectName(u"closeAppBtn")
        self.closeAppBtn.setMinimumSize(QSize(28, 28))
        self.closeAppBtn.setMaximumSize(QSize(28, 28))
        self.closeAppBtn.setCursor(QCursor(Qt.PointingHandCursor))
        iconClose = QIcon()
        iconClose.addFile(":/icons/images/icons/cil-x.png", QSize(), QIcon.Normal, QIcon.Off)
        self.closeAppBtn.setIcon(iconClose)
        self.closeAppBtn.setIconSize(QSize(20, 20))

        self.horizontalLayout_2.addWidget(self.closeAppBtn)

        self.horizontalLayout.addWidget(self.rightButtons, 0, Qt.AlignRight)

        self.verticalLayout_2.addWidget(self.contentTopBg)

        self.contentBottom = QFrame(self.contentBox)
        self.contentBottom.setObjectName(u"contentBottom")
        self.contentBottom.setFrameShape(QFrame.NoFrame)
        self.contentBottom.setFrameShadow(QFrame.Raised)
        self.verticalLayout_6 = QVBoxLayout(self.contentBottom)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.content = QFrame(self.contentBottom)
        self.content.setObjectName(u"content")
        self.content.setFrameShape(QFrame.NoFrame)
        self.content.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_4 = QHBoxLayout(self.content)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.pagesContainer = QFrame(self.content)
        self.pagesContainer.setObjectName(u"pagesContainer")
        self.pagesContainer.setStyleSheet(u"")
        self.pagesContainer.setFrameShape(QFrame.NoFrame)
        self.pagesContainer.setFrameShadow(QFrame.Raised)
        self.verticalLayout_15 = QVBoxLayout(self.pagesContainer)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName(u"verticalLayout_15")
        self.verticalLayout_15.setContentsMargins(10, 10, 10, 10)
        self.stackedWidget = QStackedWidget(self.pagesContainer)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setStyleSheet(u"background: transparent;")

        self.verticalLayout_15.addWidget(self.stackedWidget)

        self.horizontalLayout_4.addWidget(self.pagesContainer)

        self.extraRightBox = QFrame(self.content)
        self.extraRightBox.setObjectName(u"extraRightBox")
        self.extraRightBox.setMinimumSize(QSize(0, 0))
        self.extraRightBox.setMaximumSize(QSize(0, 16777215))
        self.extraRightBox.setFrameShape(QFrame.NoFrame)
        self.extraRightBox.setFrameShadow(QFrame.Raised)
        self.verticalLayout_7 = QVBoxLayout(self.extraRightBox)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.themeSettingsTopDetail = QFrame(self.extraRightBox)
        self.themeSettingsTopDetail.setObjectName(u"themeSettingsTopDetail")
        self.themeSettingsTopDetail.setMaximumSize(QSize(16777215, 3))
        self.themeSettingsTopDetail.setFrameShape(QFrame.NoFrame)
        self.themeSettingsTopDetail.setFrameShadow(QFrame.Raised)

        self.verticalLayout_7.addWidget(self.themeSettingsTopDetail)

        self.contentSettings = QFrame(self.extraRightBox)
        self.contentSettings.setObjectName(u"contentSettings")
        self.contentSettings.setFrameShape(QFrame.NoFrame)
        self.contentSettings.setFrameShadow(QFrame.Raised)
        self.verticalLayout_13 = QVBoxLayout(self.contentSettings)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName(u"verticalLayout_13")
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.topMenus = QFrame(self.contentSettings)
        self.topMenus.setObjectName(u"topMenus")
        self.topMenus.setFrameShape(QFrame.NoFrame)
        self.topMenus.setFrameShadow(QFrame.Raised)
        self.verticalLayout_14 = QVBoxLayout(self.topMenus)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName(u"verticalLayout_14")
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)

        self.verticalLayout_13.addWidget(self.topMenus, 0, Qt.AlignTop)

        self.verticalLayout_7.addWidget(self.contentSettings)

        self.horizontalLayout_4.addWidget(self.extraRightBox)

        self.verticalLayout_6.addWidget(self.content)

        self.bottomBar = QFrame(self.contentBottom)
        self.bottomBar.setObjectName(u"bottomBar")
        self.bottomBar.setMinimumSize(QSize(0, 22))
        self.bottomBar.setMaximumSize(QSize(16777215, 22))
        self.bottomBar.setFrameShape(QFrame.NoFrame)
        self.bottomBar.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_5 = QHBoxLayout(self.bottomBar)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.creditsLabel = QLabel(self.bottomBar)
        self.creditsLabel.setObjectName(u"creditsLabel")
        self.creditsLabel.setMaximumSize(QSize(16777215, 16))
        font5 = QFont()
        font5.setFamily(u"Segoe UI")
        font5.setBold(False)
        font5.setItalic(False)
        self.creditsLabel.setFont(font5)
        self.creditsLabel.setAlignment(Qt.AlignLeading | Qt.AlignLeft | Qt.AlignVCenter)

        self.horizontalLayout_5.addWidget(self.creditsLabel)

        self.frame_size_grip = QFrame(self.bottomBar)
        self.frame_size_grip.setObjectName(u"frame_size_grip")
        self.frame_size_grip.setMinimumSize(QSize(20, 0))
        self.frame_size_grip.setMaximumSize(QSize(20, 16777215))
        self.frame_size_grip.setFrameShape(QFrame.NoFrame)
        self.frame_size_grip.setFrameShadow(QFrame.Raised)

        self.horizontalLayout_5.addWidget(self.frame_size_grip)

        self.verticalLayout_6.addWidget(self.bottomBar)

        self.verticalLayout_2.addWidget(self.contentBottom)

        self.appLayout.addWidget(self.contentBox)

        self.windowMargins.addWidget(self.bgApp)

        MainWindow.setCentralWidget(self.mainWindowWidget)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(2)

        QMetaObject.connectSlotsByName(MainWindow)

        # Kafka Window
        self.kafkaWindow = QWidget(MainWindow)
        self.kafkaWindowVerticalLayout = QVBoxLayout(self.kafkaWindow)
        self.kafkaWindowLabel = QLabel("Kafka Address")
        self.kafkaWindowTextEdit = QLineEdit()
        self.kafkaWindowButton = QPushButton("Connect")
        self.kafkaWindowVerticalLayout.addWidget(self.kafkaWindowLabel)
        self.kafkaWindowVerticalLayout.addWidget(self.kafkaWindowTextEdit)
        self.kafkaWindowVerticalLayout.addWidget(self.kafkaWindowButton)
        self.stackedWidget.addWidget(self.kafkaWindow)
        # End Kafka Window

        # Login Window
        self.loginWindow = QWidget(MainWindow)
        self.loginWindowLayout = QVBoxLayout(self.loginWindow)
        self.loginUsernameLabel = QLabel("Username")
        self.loginPasswordLabel = QLabel("Password")
        self.loginUsernameEdit = QLineEdit()
        self.loginPasswordEdit = QLineEdit()
        self.loginButton = QPushButton("Connect")
        self.loginWindowLayout.addWidget(self.loginUsernameLabel)
        self.loginWindowLayout.addWidget(self.loginUsernameEdit)
        self.loginWindowLayout.addWidget(self.loginPasswordLabel)
        self.loginWindowLayout.addWidget(self.loginPasswordEdit)
        self.loginWindowLayout.addWidget(self.loginButton)
        self.stackedWidget.addWidget(self.loginWindow)
        # End Login Window

        # Register Window
        self.registerWindow = QWidget(MainWindow)
        self.registerWindowLayout = QVBoxLayout(self.registerWindow)
        self.registerUsernameLabel = QLabel("Username")
        self.registerPasswordLabel = QLabel("Password")
        self.registerConfirmPasswordLabel = QLabel("Confirm Password")
        self.registerUsernameEdit = QLineEdit()
        self.registerPasswordEdit = QLineEdit()
        self.registerConfirmPasswordEdit = QLineEdit()
        self.registerButton = QPushButton("Connect")
        self.registerWindowLayout.addWidget(self.registerUsernameLabel)
        self.registerWindowLayout.addWidget(self.registerUsernameEdit)
        self.registerWindowLayout.addWidget(self.registerPasswordLabel)
        self.registerWindowLayout.addWidget(self.registerPasswordEdit)
        self.registerWindowLayout.addWidget(self.registerConfirmPasswordLabel)
        self.registerWindowLayout.addWidget(self.registerConfirmPasswordEdit)
        self.registerWindowLayout.addWidget(self.registerButton)
        self.stackedWidget.addWidget(self.registerWindow)
        # End register Window

        # Call Window
        self.callWindow = QWidget(MainWindow)
        self.callWindowLayout = QVBoxLayout(self.callWindow)

        self.callUserCallKeyLabel = QLabel("Call Key")
        self.callUserCallPasswordLabel = QLabel("Call Password")
        self.callUserCallKeyEdit = QLineEdit()
        self.callUserCallKeyEdit.setReadOnly(True)
        self.callUserCallPasswordEdit = QLineEdit()
        self.callUserCallPasswordEdit.setReadOnly(True)
        self.callStartSharingButton = QPushButton("Start Sharing")
        self.callWindowLayout.addWidget(self.callUserCallKeyLabel)
        self.callWindowLayout.addWidget(self.callUserCallKeyEdit)
        self.callWindowLayout.addWidget(self.callUserCallPasswordLabel)
        self.callWindowLayout.addWidget(self.callUserCallPasswordEdit)
        self.callWindowLayout.addWidget(self.callStartSharingButton)

        self.callPartnerCallKeyLabel = QLabel("Call Key")
        self.callPartnerCallPasswordLabel = QLabel("Call Password")
        self.callPartnerCallKeyEdit = QLineEdit()
        self.callPartnerCallPasswordEdit = QLineEdit()
        self.callJoinSessionButton = QPushButton("Join Session")
        self.callWindowLayout.addWidget(self.callPartnerCallKeyLabel)
        self.callWindowLayout.addWidget(self.callPartnerCallKeyEdit)
        self.callWindowLayout.addWidget(self.callPartnerCallPasswordLabel)
        self.callWindowLayout.addWidget(self.callPartnerCallPasswordEdit)
        self.callWindowLayout.addWidget(self.callJoinSessionButton)

        self.stackedWidget.addWidget(self.callWindow)
        # End Call Window

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.titleLeftApp.setText(QCoreApplication.translate("MainWindow", u"PyDracula", None))
        self.titleLeftDescription.setText(QCoreApplication.translate("MainWindow", u"Modern GUI / Flat Style", None))
        self.toggleButton.setText(QCoreApplication.translate("MainWindow", u"Hide", None))
        self.btnKafka.setText(QCoreApplication.translate("MainWindow", u"Kafka", None))
        self.btnLogin.setText(QCoreApplication.translate("MainWindow", u"Login", None))
        self.btnRegister.setText(QCoreApplication.translate("MainWindow", u"Register", None))
        self.btnCall.setText(QCoreApplication.translate("MainWindow", u"Call", None))
        self.btnChangeTheme.setText(QCoreApplication.translate("MainWindow", u"Change Theme", None))
        self.titleRightInfo.setText(
            QCoreApplication.translate("MainWindow", u"PyDracula APP - Theme with colors based on Dracula for Python.",
                                       None))
        self.minimizeAppBtn.setToolTip(QCoreApplication.translate("MainWindow", u"Minimize", None))
        self.minimizeAppBtn.setText("")
        self.maximizeRestoreAppBtn.setToolTip(QCoreApplication.translate("MainWindow", u"Maximize", None))
        self.maximizeRestoreAppBtn.setText("")
        self.closeAppBtn.setToolTip(QCoreApplication.translate("MainWindow", u"Close", None))
        self.closeAppBtn.setText("")
        self.creditsLabel.setText(QCoreApplication.translate("MainWindow", u"By: Tutuianu Robert", None))

