# Form implementation generated from reading ui file 'VideoWidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
from typing import Callable

from PySide6 import QtCore, QtWidgets


class MyVideosWindow(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.scrollAreaLayout = QtWidgets.QVBoxLayout(self)
        self.scrollArea = QtWidgets.QScrollArea(self)
        self.scrollAreaLayout.addWidget(self.scrollArea)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")

        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

    def addVideoRow(self, durationLabelText: str, sizeLabelText: str, createdAtLabelText: str, callback: Callable):
        horizontalLayout = QtWidgets.QHBoxLayout()
        horizontalLayout.setObjectName("horizontalLayout")
        durationLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        durationLabel.setObjectName("label")
        durationLabel.setText(durationLabelText)
        horizontalLayout.addWidget(durationLabel)
        sizeLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        sizeLabel.setObjectName("label_2")
        horizontalLayout.addWidget(sizeLabel)
        sizeLabel.setText(sizeLabelText)
        createdAtLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        createdAtLabel.setObjectName("label_3")
        createdAtLabel.setText(createdAtLabelText)
        horizontalLayout.addWidget(createdAtLabel)
        pushButton = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        pushButton.setObjectName("pushButton")
        pushButton.setText("DOWNLOAD")
        pushButton.clicked.connect(callback)
        horizontalLayout.addWidget(pushButton)
        self.verticalLayout.addLayout(horizontalLayout)

    def clear(self):
        self.clearLayout(self.verticalLayout)

    def clearLayout(self, layout):
        while layout.count():
            child = layout.takeAt(0)
            if child.widget():
                child.widget().deleteLater()
            if child.layout():
                self.clearLayout(child.layout())


