#!/bin/sh

cd VideoMicroservice
go build VideoMicroservice.go recorder.go resizer.go screenshot.go screen.go byte_image.go
cd ..

cd AggregatorMicroservice
go build AggregatorMicroservice.go
cd ..

cd DatabaseMicroservice
go build DatabaseMicroservice.go
cd ..

#cd PingMicroservice
#go build PingMicroservice.go