#!/bin/sh

cd VideoMicroservice
go build VideoMicroservice.go recorder.go resizer.go screenshot.go screen.go byte_image.go
cd ..

cd AggregatorMicroservice
go build AggregatorMicroservice.go
cd ..

cd UI
go build UI.go
cd ..

cd MergerMicroservice
go build MergerMicroservice.go
cd ..

cd DatabaseMicroservice
go build DatabaseMicroservice.go
cd ..

cd PindMicroservice
go build PindMicroservice.go