#!/bin/sh

ffmpeg -y -i "$1" -i "$2" -map 0:v -map 1:a -tune zerolatency -preset ultrafast -shortest -movflags frag_keyframe+empty_moov+default_base_moof+faststart -shortest -profile:v baseline -f mp4 -b "$3" pipe:1