#!/bin/sh

# shellcheck disable=SC2006
./build
# shellcheck disable=SC2046
timestamp=`expr $(date +"%s") + 2`
xterm -hold -T "Aggregator" -e ./AggregatorMicroservice/AggregatorMicroservice &
xterm -hold -T "Video" -e ./VideoMicroservice/VideoMicroservice "$timestamp" &
xterm -hold -T "Audio" -e venv/bin/python3 AudioMicroservice/AudioMicroservice.py "$timestamp" &
#xterm -hold -T "InputListener" -e venv/bin/python3 InputExecutorMicroservice/InputExecutorMicroservice.py &
xterm -hold -T "Ping" -e ./PingMicroservice/PingMicroservice &
xterm -hold -T "UI" -e go run UI/UI.go