#!/bin/sh

EXTERNAL_IP=$(hostname -I | cut -d' ' -f1)
cat > docker-compose.yml << END
version: "3"

services:
  database-microservice:
    image: database-microservice:v12
    container_name: 'database-microservice'
    environment:
      - BROKER_ADDRESS=localhost:9092
      - DATABASE_USER=robert
      - DATABASE_PASSWORD=robert
      - DATABASE_HOST=localhost
      - DATABASE_PORT=3306
      - DATABASE_NAME=licenta
    network_mode: "host"
#    depends_on:
#      - kafka
#  zookeeper:
#    image: 'bitnami/zookeeper:latest'
#    container_name: 'zookeeper'
#    ports:
#      - "2181:2181"
#    volumes:
#      - "zookeeper_data:/bitnami"
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#  kafka:
#    image: 'bitnami/kafka:latest'
#    container_name: 'kafka'
#    ports:
#      - "9092:9092"
#    volumes:
#      - "kafka_data:/bitnami"
#    environment:
#      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://$EXTERNAL_IP:9092
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_CFG_MAX_PARTITION_FETCH_BYTES=10485760
#      - KAFKA_CFG_MAX_REQUEST_SIZE=10485760
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    depends_on:
#      - zookeeper
#    healthcheck:
#      test: ["CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181"]
#      interval: 5s
#      timeout: 10s
#      retries: 5
#
#volumes:
#  zookeeper_data:
#    driver: local
#  kafka_data:
#    driver: local

END
sudo docker-compose up -d