# Form implementation generated from reading ui file 'VideoWidget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
from typing import Callable


class VideoWidget(QtWidgets.QWidget):
    def __init__(self, Form, durationLabelText: str, sizeLabelText: str, createdAtLabelText: str, callback: Callable):
        super().__init__()
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.durationLabel = QtWidgets.QLabel(parent=self)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.durationLabel.setFont(font)
        self.durationLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.durationLabel.setObjectName("durationLabel")
        self.horizontalLayout.addWidget(self.durationLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.sizeLabel = QtWidgets.QLabel(parent=self)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sizeLabel.setFont(font)
        self.sizeLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sizeLabel.setObjectName("sizeLabel")
        self.horizontalLayout.addWidget(self.sizeLabel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.createdAtLabel = QtWidgets.QLabel(parent=self)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.createdAtLabel.setFont(font)
        self.createdAtLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.createdAtLabel.setObjectName("createdAtLabel")
        self.horizontalLayout.addWidget(self.createdAtLabel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.downloadButton = QtWidgets.QPushButton(parent=self)
        self.downloadButton.clicked.connect(callback)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.downloadButton.setFont(font)
        self.downloadButton.setObjectName("downloadButton")
        self.horizontalLayout.addWidget(self.downloadButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        QtCore.QMetaObject.connectSlotsByName(Form)

        _translate = QtCore.QCoreApplication.translate
        self.durationLabel.setText(_translate("Form", durationLabelText))
        self.sizeLabel.setText(_translate("Form", sizeLabelText))
        self.createdAtLabel.setText(_translate("Form", createdAtLabelText))
        self.downloadButton.setText(_translate("Form", "DOWNLOAD"))
