#!/bin/sh

cd ..

go build -o VideoMicroservice.exe ./VideoMicroservice/VideoMicroservice.go ./VideoMicroservice/recorder.go ./VideoMicroservice/resizer.go ./VideoMicroservice/screenshot.go ./VideoMicroservice/screen.go ./VideoMicroservice/byte_image.go

go build -o AggregatorMicroservice.exe AggregatorMicroservice/AggregatorMicroservice.go AggregatorMicroservice/AudioVideoPair.go

mv VideoMicroservice.exe UI/VideoMicroservice
mv AggregatorMicroservice.exe UI/AggregatorMicroservice
chmod +x UI/VideoMicroservice
chmod +x UI/AggregatorMicroservice

#cd PingMicroservice
#go build PingMicroservice.go